name: background_service_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_background_service: ^2.4.6
  get_storage: ^2.1.1
  get: 4.6.5
  shared_preferences: ^2.0.18
  device_info_plus: ^8.1.0
  flutter_local_notifications: ^13.0.0
  http_interceptor: ^1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

